#!/bin/sh
babel src --out-dir lib
rm -rf tmp
mkdir tmp
cp -a lib tmp/lib
cp index.js tmp/index.js
cp config.js tmp/config.js
cp package.json tmp/package.json
cd tmp
NODE_ENV=production npm install
zip -r <%= functionName %>.zip ./
cd ..
